-- Índices para otimização de consultas frequentes

-- Índices para tabela PREFERENCIAS_NOTIFICACAO
CREATE INDEX IDX_PREF_CIDADE_ESTADO ON PREFERENCIAS_NOTIFICACAO(CIDADE, ESTADO);
CREATE INDEX IDX_PREF_TEMPERATURA ON PREFERENCIAS_NOTIFICACAO(TEMPERATURA_MIN, TEMPERATURA_MAX);
CREATE INDEX IDX_PREF_ATIVO ON PREFERENCIAS_NOTIFICACAO(ATIVO);

-- Índices para tabela ALERTA_TEMPERATURA
CREATE INDEX IDX_ALERTA_DATA ON ALERTA_TEMPERATURA(DATA_HORA);
CREATE INDEX IDX_ALERTA_CIDADE_ESTADO ON ALERTA_TEMPERATURA(CIDADE, ESTADO);
CREATE INDEX IDX_ALERTA_TEMPERATURA ON ALERTA_TEMPERATURA(TEMPERATURA);
CREATE INDEX IDX_ALERTA_STATUS ON ALERTA_TEMPERATURA(STATUS);
