-- Dados de exemplo para ambiente de desenvolvimento

-- Preferências de notificação iniciais
INSERT INTO PREFERENCIAS_NOTIFICACAO (
    ID_PREFERENCIA, CIDADE, ESTADO, TEMPERATURA_MIN, TEMPERATURA_MAX, ATIVO, DATA_CRIACAO
) VALUES (
    SEQ_PREFERENCIA.NEXTVAL, 'São Paulo', 'SP', 15, 30, 'S', SYSTIMESTAMP
);

INSERT INTO PREFERENCIAS_NOTIFICACAO (
    ID_PREFERENCIA, CIDADE, ESTADO, TEMPERATURA_MIN, TEMPERATURA_MAX, ATIVO, DATA_CRIACAO
) VALUES (
    SEQ_PREFERENCIA.NEXTVAL, 'Rio de Janeiro', 'RJ', 18, 32, 'S', SYSTIMESTAMP
);

INSERT INTO PREFERENCIAS_NOTIFICACAO (
    ID_PREFERENCIA, CIDADE, ESTADO, TEMPERATURA_MIN, TEMPERATURA_MAX, ATIVO, DATA_CRIACAO
) VALUES (
    SEQ_PREFERENCIA.NEXTVAL, 'Curitiba', 'PR', 10, 28, 'S', SYSTIMESTAMP
);

-- Alguns alertas históricos
INSERT INTO ALERTA_TEMPERATURA (
    ID_ALERTA, CIDADE, ESTADO, TEMPERATURA, TIPO_ALERTA, MENSAGEM, DATA_HORA, STATUS
) VALUES (
    SEQ_ALERTA.NEXTVAL, 'São Paulo', 'SP', 32.5, 'ALTO', 
    'Temperatura acima do limite máximo configurado', SYSTIMESTAMP - INTERVAL '1' DAY, 'INATIVO'
);

INSERT INTO ALERTA_TEMPERATURA (
    ID_ALERTA, CIDADE, ESTADO, TEMPERATURA, TIPO_ALERTA, MENSAGEM, DATA_HORA, STATUS
) VALUES (
    SEQ_ALERTA.NEXTVAL, 'Curitiba', 'PR', 8.5, 'BAIXO', 
    'Temperatura abaixo do limite mínimo configurado', SYSTIMESTAMP - INTERVAL '2' DAY, 'INATIVO'
);

INSERT INTO ALERTA_TEMPERATURA (
    ID_ALERTA, CIDADE, ESTADO, TEMPERATURA, TIPO_ALERTA, MENSAGEM, DATA_HORA, STATUS
) VALUES (
    SEQ_ALERTA.NEXTVAL, 'Rio de Janeiro', 'RJ', 34.0, 'ALTO', 
    'Temperatura acima do limite máximo configurado', SYSTIMESTAMP, 'ATIVO'
);

COMMIT;
