@baseUrl = http://localhost:5231

### Preferências de Notificação

### Listar todas as preferências
GET {{baseUrl}}/api/Preferencias
Accept: application/json

### Listar preferências por cidade
GET {{baseUrl}}/api/Preferencias?cidade=São Paulo
Accept: application/json

### Obter preferência por ID
GET {{baseUrl}}/api/Preferencias/1
Accept: application/json

### Criar nova preferência
POST {{baseUrl}}/api/Preferencias
Content-Type: application/json

{
    "cidade": "São Paulo",
    "estado": "SP",
    "temperaturaMinima": 15,
    "temperaturaMaxima": 30,
    "intervaloVerificacao": 60
}

### Atualizar preferência existente
PUT {{baseUrl}}/api/Preferencias/1
Content-Type: application/json

{
    "idPreferencia": 1,
    "cidade": "São Paulo",
    "estado": "SP",
    "temperaturaMinima": 18,
    "temperaturaMaxima": 28,
    "intervaloVerificacao": 30
}

### Excluir preferência
DELETE {{baseUrl}}/api/Preferencias/1

### Alertas de Temperatura

### Listar todos os alertas
GET {{baseUrl}}/api/Alerta
Accept: application/json

### Listar alertas por cidade
GET {{baseUrl}}/api/Alerta?cidade=São Paulo
Accept: application/json

### Obter alerta por ID
GET {{baseUrl}}/api/Alerta/1
Accept: application/json

### Atualizar status do alerta
PUT {{baseUrl}}/api/Alerta/1/status 
Content-Type: application/json

"INATIVO"

POST {{baseUrl}}/api/Alerta/check
Accept: application/json


POST http://localhost:5231/api/Alerta
Content-Type: application/json

{
  "cidade": "São Paulo",
  "estado": "SP",
  "temperaturaLimite": 35,
  "status": "ATIVO",
  "tipoAlerta": "ALTA",
  "mensagem": "Temperatura acima do limite"
}